/**
 * Printable preview page.
 *
 * Fallback / companion to the automatic PDF download. Renders the last
 * parsed Bill Status result from chrome.storage.session (memory only).
 * The document is built with DOM APIs from the structured data, so no HTML
 * string from IREPS is ever inserted into the page.
 *
 * Buttons:
 *   Download PDF        - generates the PDF in this page and saves it
 *   Print / Save as PDF - Chrome's print dialog (choose "Save as PDF")
 */

import { BILL_FIELDS, LONG_TEXT_FIELDS } from "../services/bill-parser.js";
import { generateBillStatusPdf } from "../services/pdf-service.js";
import { downloadPdf } from "../services/download-service.js";
import { SESSION_KEYS } from "../utils/messages.js";

const root = document.getElementById("document");
const notice = document.getElementById("notice");
const btnDownload = document.getElementById("btn-download");
const btnPrint = document.getElementById("btn-print");

let currentResult = null;

function h(tag, className, text) {
  const node = document.createElement(tag);
  if (className) node.className = className;
  if (text !== undefined && text !== null) node.textContent = String(text);
  return node;
}

const display = (v) => (v === null || v === undefined || String(v).trim() === "" ? "-" : String(v));

function renderDocument(result) {
  root.replaceChildren();
  const doc = h("div", "doc");
  doc.append(h("h1", null, "IREPS BILL STATUS"));

  const meta = h("section", "meta");
  for (const [k, v] of [
    ["Source:", "Indian Railways IREPS"],
    ["Retrieved:", result.retrievedAt],
    ["Filter:", result.filter],
    ["Records:", result.recordCount]
  ]) {
    const line = h("div");
    line.append(h("span", "k", k), document.createTextNode(display(v)));
    meta.append(line);
  }
  doc.append(meta);

  if (!result.bills || result.bills.length === 0) {
    const empty = h("section", "empty");
    empty.append(
      h("h2", null, "No Bill Records Found"),
      h("p", null, result.pageMessage || "IREPS returned successfully, but no bill records were available for the selected period.")
    );
    doc.append(empty);
  } else {
    for (const bill of result.bills) {
      const article = h("article", "bill");
      const head = h("header", "bill-head");
      head.append(h("span", null, `Bill #${bill.index}`), h("span", "status", display(bill.status)));
      article.append(head);

      const grid = h("div", "grid");
      const addRow = (label, value, long) => {
        const row = h("div", long ? "row long" : "row");
        row.append(h("div", "label", `${label}:`), h("div", "value", display(value)));
        grid.append(row);
      };
      for (const field of BILL_FIELDS) addRow(field.label, bill[field.key], LONG_TEXT_FIELDS.has(field.key));
      for (const [label, value] of Object.entries(bill.extra || {})) addRow(label, value, true);
      article.append(grid);
      doc.append(article);
    }
  }

  doc.append(
    h("footer", "doc-footer", "Generated by DocLink from the authenticated IREPS session. Values are reproduced exactly as returned by IREPS.")
  );
  root.append(doc);
  document.title = `IREPS Bill Status - ${result.retrievedAt} - DocLink`;
}

function showNotice(text) {
  notice.textContent = text;
  notice.hidden = !text;
}

async function load() {
  try {
    const stored = await chrome.storage.session.get(SESSION_KEYS.LAST_RESULT);
    currentResult = stored[SESSION_KEYS.LAST_RESULT] || null;
  } catch {
    currentResult = null;
  }
  if (!currentResult) {
    root.replaceChildren(h("p", "placeholder", "No Bill Status has been retrieved in this browser session yet. Open DocLink and click Download Bill Status first."));
    btnDownload.disabled = true;
    btnPrint.disabled = true;
    return;
  }
  renderDocument(currentResult);
}

btnPrint.addEventListener("click", () => window.print());

btnDownload.addEventListener("click", async () => {
  if (!currentResult) return;
  btnDownload.disabled = true;
  showNotice("");
  try {
    const pdf = await generateBillStatusPdf(currentResult);
    const download = await downloadPdf(pdf.bytes);
    showNotice(`Saved ${download.filename} to Downloads/DocLink/IREPS.`);
  } catch (error) {
    console.warn("[DocLink] preview download failed", error && error.message);
    showNotice("DocLink could not generate or save the PDF here. Use Print / Save as PDF instead.");
  } finally {
    btnDownload.disabled = false;
  }
});

load();
